<!doctype html>
<html lang="lt">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="css/app.css" rel="stylesheet">
    <title>WeatherApp</title>
</head>
<body>
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 m-auto">
            <h3 class="text-center mb-3">
                <img src="img/lt_transparent.png"> Orai Lietuvoje
            </h3>
            <div class="form-group">
                <input type="text" id="search" class="form-control form-control-lg"
                       placeholder="Įveskite miesto pavadinimą">

            </div>
            <div id="match-list"></div>
        </div>
    </div>
    <div id="some-info" class="d-inline-flex flex-wrap justify-content-between"></div>
</div>

<script src="js/app.js"></script>
</body>
</html>